all:
	g++ -Wall -o 94 94.cpp -std=c++11 -lpthread
	g++ -Wall -o 98 98.cpp -std=c++11 -lpthread
	g++ -Wall -o 100 100.cpp -std=c++11 -lpthread
	g++ -Wall -o 101 101.cpp -std=c++11 -lpthread
	g++ -Wall -o 102 102.cpp -std=c++11 -lpthread
	g++ -Wall -o 103 103.cpp -std=c++11 -lpthread
	g++ -Wall -o 104 104.cpp -std=c++11 -lpthread
	g++ -Wall -o 105 105.cpp -std=c++11 -lpthread
	g++ -Wall -o 107 107.cpp -std=c++11 -lpthread
clean:
	rm 94 98 100 101 102 103 104 105 107
94:
	g++ -Wall -o 94 94.cpp -std=c++11 -lpthread
98:
	g++ -Wall -o 98 98.cpp -std=c++11 -lpthread
100:
	g++ -Wall -o 100 100.cpp -std=c++11 -lpthread
101:
	g++ -Wall -o 101 101.cpp -std=c++11 -lpthread
102:
	g++ -Wall -o 102 102.cpp -std=c++11 -lpthread
103:
	g++ -Wall -o 103 103.cpp -std=c++11 -lpthread
104:
	g++ -Wall -o 104 104.cpp -std=c++11 -lpthread
105:
	g++ -Wall -o 105 105.cpp -std=c++11 -lpthread
107:
	g++ -Wall -o 107 107.cpp -std=c++11 -lpthread