all:
	g++ -Wall -o 100 100.cpp -std=c++11 -lpthread
	g++ -Wall -o 101 101.cpp -std=c++11 -lpthread
	g++ -Wall -o 104 104.cpp -std=c++11 -lpthread
clean:
	rm 100 101 104
100:
	g++ -Wall -o 100 100.cpp -std=c++11 -lpthread
101:
	g++ -Wall -o 101 101.cpp -std=c++11 -lpthread
104:
	g++ -Wall -o 104 104.cpp -std=c++11 -lpthread