all:
	g++ -Wall -o 94 94.cpp -std=c++11 -lpthread
	g++ -Wall -o 98 98.cpp -std=c++11 -lpthread
	g++ -Wall -o 100 100.cpp -std=c++11 -lpthread
	g++ -Wall -o 101 101.cpp -std=c++11 -lpthread
	g++ -Wall -o 102 102.cpp -std=c++11 -lpthread
	g++ -Wall -o 103 103.cpp -std=c++11 -lpthread
	g++ -Wall -o 104 104.cpp -std=c++11 -lpthread
	g++ -Wall -o 105 105.cpp -std=c++11 -lpthread
	g++ -Wall -o 106 106.cpp -std=c++11 -lpthread
	g++ -Wall -o 107 107.cpp -std=c++11 -lpthread
	g++ -Wall -o 112 112.cpp -std=c++11 -lpthread
	g++ -Wall -o 113 113.cpp -std=c++11 -lpthread
	g++ -Wall -o 144 144.cpp -std=c++11 -lpthread
	g++ -Wall -o 145 145.cpp -std=c++11 -lpthread
	g++ -Wall -o 515 515.cpp -std=c++11 -lpthread
	g++ -Wall -o 617 617.cpp -std=c++11 -lpthread
clean:
	rm 94 98 100 101 102 103 104 105 106 107 112 113 144 145 515 617
94:
	g++ -Wall -o 94 94.cpp -std=c++11 -lpthread
98:
	g++ -Wall -o 98 98.cpp -std=c++11 -lpthread
100:
	g++ -Wall -o 100 100.cpp -std=c++11 -lpthread
101:
	g++ -Wall -o 101 101.cpp -std=c++11 -lpthread
102:
	g++ -Wall -o 102 102.cpp -std=c++11 -lpthread
103:
	g++ -Wall -o 103 103.cpp -std=c++11 -lpthread
104:
	g++ -Wall -o 104 104.cpp -std=c++11 -lpthread
105:
	g++ -Wall -o 105 105.cpp -std=c++11 -lpthread
106:
	g++ -Wall -o 106 106.cpp -std=c++11 -lpthread
107:
	g++ -Wall -o 107 107.cpp -std=c++11 -lpthread
112:
	g++ -Wall -o 112 112.cpp -std=c++11 -lpthread
113:
	g++ -Wall -o 113 113.cpp -std=c++11 -lpthread
144:
	g++ -Wall -o 144 144.cpp -std=c++11 -lpthread
145:
	g++ -Wall -o 145 145.cpp -std=c++11 -lpthread
515:
	g++ -Wall -o 515 515.cpp -std=c++11 -lpthread
617:
	g++ -Wall -o 617 617.cpp -std=c++11 -lpthread