all:
	g++ -Wall -o 56 56.cpp -std=c++11 -lpthread
	g++ -Wall -o 57 57.cpp -std=c++11 -lpthread
clean:
	rm 56 57
56:
	g++ -Wall -o 56 56.cpp -std=c++11 -lpthread
57:
	g++ -Wall -o 57 57.cpp -std=c++11 -lpthread