all:
	g++ -Wall -o 56 56.cpp -std=c++11 -lpthread
	g++ -Wall -o 57 57.cpp -std=c++11 -lpthread
	g++ -Wall -o 75 75.cpp -std=c++11 -lpthread
	g++ -Wall -o 147 147.cpp -std=c++11 -lpthread
	g++ -Wall -o 179 179.cpp -std=c++11 -lpthread
	g++ -Wall -o 242 242.cpp -std=c++11 -lpthread
	g++ -Wall -o 349 349.cpp -std=c++11 -lpthread
clean:
	rm 56 57 75 147 179 242 349
56:
	g++ -Wall -o 56 56.cpp -std=c++11 -lpthread
57:
	g++ -Wall -o 57 57.cpp -std=c++11 -lpthread
75:
	g++ -Wall -o 75 75.cpp -std=c++11 -lpthread
147:
	g++ -Wall -o 147 147.cpp -std=c++11 -lpthread
179:
	g++ -Wall -o 179 179.cpp -std=c++11 -lpthread
242:
	g++ -Wall -o 242 242.cpp -std=c++11 -lpthread
349:
	g++ -Wall -o 349 349.cpp -std=c++11 -lpthread
