all:
	g++ -Wall -o 28 28.cpp -std=c++11 -lpthread
	g++ -Wall -o 58 58.cpp -std=c++11 -lpthread
clean:
	rm 28 58
28:
	g++ -Wall -o 28 28.cpp -std=c++11 -lpthread
58:
	g++ -Wall -o 58 58.cpp -std=c++11 -lpthread