all:
	g++ -Wall -o 28 28.cpp -std=c++11 -lpthread
	g++ -Wall -o 58 58.cpp -std=c++11 -lpthread
	g++ -Wall -o 67 67.cpp -std=c++11 -lpthread
	g++ -Wall -o 125 125.cpp -std=c++11 -lpthread
	g++ -Wall -o 344 344.cpp -std=c++11 -lpthread
	g++ -Wall -o 345 345.cpp -std=c++11 -lpthread
	g++ -Wall -o 387 387.cpp -std=c++11 -lpthread
	g++ -Wall -o 520 520.cpp -std=c++11 -lpthread
	g++ -Wall -o 680 680.cpp -std=c++11 -lpthread
	g++ -Wall -o 709 709.cpp -std=c++11 -lpthread
	g++ -Wall -o 819 819.cpp -std=c++11 -lpthread
clean:
	rm 28 58 67 125 344 345 387 520 680 709 819
28:
	g++ -Wall -o 28 28.cpp -std=c++11 -lpthread
58:
	g++ -Wall -o 58 58.cpp -std=c++11 -lpthread
67:
	g++ -Wall -o 67 67.cpp -std=c++11 -lpthread
125:
	g++ -Wall -o 125 125.cpp -std=c++11 -lpthread
344:
	g++ -Wall -o 344 344.cpp -std=c++11 -lpthread
345:
	g++ -Wall -o 345 345.cpp -std=c++11 -lpthread
387:
	g++ -Wall -o 387 387.cpp -std=c++11 -lpthread
520:
	g++ -Wall -o 520 520.cpp -std=c++11 -lpthread
680:
	g++ -Wall -o 680 680.cpp -std=c++11 -lpthread
709:
	g++ -Wall -o 709 709.cpp -std=c++11 -lpthread
819:
	g++ -Wall -o 819 819.cpp -std=c++11 -lpthread