all:
	g++ -Wall -o 27 27.cpp -std=c++11 -lpthread
	g++ -Wall -o 48 48.cpp -std=c++11 -lpthread
	g++ -Wall -o 54 54.cpp -std=c++11 -lpthread
	g++ -Wall -o 59 59.cpp -std=c++11 -lpthread
	g++ -Wall -o 88 88.cpp -std=c++11 -lpthread
clean:
	rm 27 48 54 59 88
27:
	g++ -Wall -o 27 27.cpp -std=c++11 -lpthread
48:
	g++ -Wall -o 48 48.cpp -std=c++11 -lpthread
54:
	g++ -Wall -o 54 54.cpp -std=c++11 -lpthread
59:
	g++ -Wall -o 59 59.cpp -std=c++11 -lpthread
88:
	g++ -Wall -o 88 88.cpp -std=c++11 -lpthread