all:
	g++ -Wall -o 27 27.cpp -std=c++11 -lpthread
	g++ -Wall -o 54 54.cpp -std=c++11 -lpthread
	g++ -Wall -o 88 88.cpp -std=c++11 -lpthread
clean:
	rm 27 54 88
27:
	g++ -Wall -o 27 27.cpp -std=c++11 -lpthread
54:
	g++ -Wall -o 54 54.cpp -std=c++11 -lpthread
88:
	g++ -Wall -o 88 88.cpp -std=c++11 -lpthread