all:
	g++ -Wall -o 20 20.cpp -std=c++11 -lpthread
	g++ -Wall -o 150 150.cpp -std=c++11 -lpthread
clean:
	rm 20 150
20:
	g++ -Wall -o 20 20.cpp -std=c++11 -lpthread
150:
	g++ -Wall -o 150 150.cpp -std=c++11 -lpthread
