all:
	g++ -Wall -o list list.cpp -std=c++11 -lpthread
	g++ -Wall -o hasCycle hasCycle.cpp -std=c++11 -lpthread
clean:
	rm list hasCycle
list:
	g++ -Wall -o list list.cpp -std=c++11 -lpthread
hasCycle:
	g++ -Wall -o hasCycle hasCycle.cpp -std=c++11 -lpthread