all:
	g++ -Wall -o list list.cpp -std=c++11 -lpthread
	g++ -Wall -o 141 141.cpp -std=c++11 -lpthread
	g++ -Wall -o 203 203.cpp -std=c++11 -lpthread
	g++ -Wall -o 206 206.cpp -std=c++11 -lpthread
clean:
	rm list 141 203 206
list:
	g++ -Wall -o list list.cpp -std=c++11 -lpthread
141:
	g++ -Wall -o 141 141.cpp -std=c++11 -lpthread
203:
	g++ -Wall -o 203 203.cpp -std=c++11 -lpthread
206:
	g++ -Wall -o 206 206.cpp -std=c++11 -lpthread